CREATE TABLE Follower (
    UserId INTEGER NOT NULL,
    FollowerId INTEGER NOT NULL,
    PRIMARY KEY (UserId, FollowerId),
    FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
    FOREIGN KEY (FollowerId) REFERENCES User(UserId) ON DELETE CASCADE
);